# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FinalProject_Insgram' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FinalProject_Insgram
  pod 'Firebase/Auth'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'

end
